#spring
spring:
#数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.99.237:3306/crawler?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: huaidou
    password: lsp763498085
    hikari:
      maximum-pool-size: 15
      max-lifetime: 1765000
      connection-timeout: 6000
#mvc
  mvc:
      view:
        prefix: classpath:templates/
        suffix: .html
#server
server:
  port: 8081

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  check-config-location: true
  type-aliases-package: cn.edu.zzti.bibased.dto


#http
http:
    request:
            connectionRequestTimeout: 500  #从连接池中获取到连接的最长时间
            connectTimeout: 5000
            socketTimeout: 30000  #数据传输的最长时间
            staleConnectionCheckEnabled: true #提交请求前测试连接是否可用
    pool:
        maxTotal: 200     #设置连接总数
        defaultMaxPerRoute: 100    #设置每个地址的并发数





